{% set name = "instanovo" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/instanovo-{{ version }}.tar.gz
  sha256: fd9cfc377d9f8da5272f96b2eb4c14c08b579d7a65466aa402601ec6c4b42672

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage(name | lower, max_pin="x.x") }}


requirements:
  host:
    - python >=3.10,<3.12
    - setuptools >=69.1.1
    - pip
  run:
    - click >=8.1.7
    - datasets >=3.0.1
    - hydra-core >=1.3.2
    - jaxtyping >=0.2.34
    - jiwer >=3.0.4
    - matchms >=0.28.1
    - neptune >=1.12.0
    - numpy >=2.0.0
    - omegaconf >=2.3.0
    - pandas >=2.2.3
    - polars >=1.9.0
    - pyopenms >=3.2.0
    - python-dotenv >=1.0.1
    - pytorch-lightning >=2.4.0
    - s3fs >=2024.6.1
    - scikit-learn >=1.5.2
    - spectrum_utils >=0.4.2
    - tensorboard >=2.18.0
    - pytorch-gpu >=2.4.1
    - tqdm >=4.66.5
    - cudatoolkit

test:
  imports:
    - instanovo
  commands:
    - pip check
    - python -c "import instanovo; print(instanovo.__version__)"
  requires:
    - pip

about:
  home: https://github.com/instadeepai/instanovo
  summary: De novo peptide sequencing with InstaNovo
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - BioGeek
  identifiers:
    - doi:10.1101/2023.08.30.555055 
